export EXA_COLORS="uu=2;37:gu=2;3;37:da=32:un=31:gn=2;3;31"
export EXA_FLAGS="--long --all --header --classify --group --color-scale --color=always --ignore-glob='.git|.DS_Store'"
# export EXA_STRICT="1"

alias l="exa $EXA_FLAGS"
alias lsi="exa $EXA_FLAGS --sort=size"
alias lmo="exa $EXA_FLAGS --sort=modified --time=modified"
alias lch="exa $EXA_FLAGS --sort=changed --time=changed"
alias lac="exa $EXA_FLAGS --sort=accessed --time=accessed"
alias lcr="exa $EXA_FLAGS --sort=created --time=created"

alias lr="exa $EXA_FLAGS --git-ignore --tree --recurse --ignore-glob='.git|.DS_Store|node_modules' --level=2"
alias lrr="exa $EXA_FLAGS --git-ignore --tree --recurse --ignore-glob='.git|.DS_Store|node_modules' --level=3"
alias lrrr="exa $EXA_FLAGS --git-ignore --tree --recurse --ignore-glob='.git|.DS_Store|node_modules' --level=4"
alias lrrrr="exa $EXA_FLAGS --git-ignore --tree --recurse --ignore-glob='.git|.DS_Store|node_modules' --level=5"
alias lra="exa $EXA_FLAGS --git-ignore --tree --recurse --ignore-glob='.git|.DS_Store|node_modules'"

alias la="exa $EXA_FLAGS --extended"
alias lar="exa $EXA_FLAGS --extended --tree --recurse --level=2"
alias larr="exa $EXA_FLAGS --extended --tree --recurse --level=3"
alias larrr="exa $EXA_FLAGS --extended --tree --recurse --level=4"
alias larrrr="exa $EXA_FLAGS --extended --tree --recurse --level=5"
alias lara="exa $EXA_FLAGS --extended --tree --recurse"
