export GEOMETRY_PROMPT_PLUGINS=(exec_time git hostname jobs node path)

export GEOMETRY_PROMPT_PATH="%3~"
export GEOMETRY_PROMPT_BASENAME=true

export PROMPT_GEOMETRY_EXEC_TIME=true
export PROMPT_GEOMETRY_COMMAND_MAX_EXEC_TIME="1"

export GEOMETRY_SYMBOL_PROMPT="➤"
export GEOMETRY_SYMBOL_RPROMPT="➜"
export GEOMETRY_SYMBOL_EXIT_VALUE="✖︎"
export GEOMETRY_SYMBOL_ROOT="⌦"

export GEOMETRY_COLOR_EXIT_VALUE="red"
export GEOMETRY_COLOR_PROMPT="magenta"
export GEOMETRY_COLOR_ROOT="yellow"
export GEOMETRY_COLOR_DIR="blue"

export GEOMETRY_PROMPT_PREFIX="\n\n"
export GEOMETRY_PROMPT_PREFIX_SPACER=" "
export GEOMETRY_PROMPT_SUFFIX=""
export GEOMETRY_SYMBOL_SPACER=" "
export GEOMETRY_DIR_SPACER=" "
export GEOMETRY_PLUGIN_SEPARATOR=" "
