alias ip="ip -human -color"
alias ipm="ip -brief"
alias ipa="ip -all -details -stats"
alias ipj="ip -all -details -stats -json"
alias ips="bhr; ip addr; bhr; ip route; ip rule | bl perl"

alias tc="tc -color -pretty"
alias tca="tc -details -statistics"
alias tcg="tc -graph"
alias tcga="tc -graph -details -statistics"
alias tcj="tc -json"
alias tcja="tc -json -details -statistics"
