alias ip="ip -human -color"
alias ipm="command ip -human -color -brief"
alias ipa="command ip -human -color -all -details -stats"
alias ipj="command ip -human -all -details -stats -json"

alias tc="tc -color -pretty"
alias tca="command tc -color -pretty -details -statistics"
alias tcg="command tc -color -pretty -graph"
alias tcga="command tc -color -pretty -graph -details -statistics"
alias tcj="command tc -json"
alias tcja="command tc -json -details -statistics"
