# alias pip='pip --target=$HOME/.virtualenv'
alias pip="python -m pip"
alias pip3="python3 -m pip"
alias pips="pip search"
alias pipi="pip show"
alias pipfs="pip show --files"
alias pipin="pip install"
alias piprm="pip uninstall --yes"
alias pipls="pip list --format columns --verbose"
alias pipout="pip list --format columns --outdated"
alias pipupg="pip install --upgrade"
