# alias pip='pip --target=$HOME/.virtualenv'
# alias pip="python3 -m pip"
alias pips="pip search"
alias pipi="pip show"
alias pipfs="pip show --files"
alias pipin="pip install --force-reinstall"
alias piprm="pip uninstall --yes"
alias pipls="pip list --verbose | bat --style=grid -l fstab"
alias pipout="pip list --outdated | bat --style=grid -l fstab"
alias pipupg="pip install --upgrade"
