alias ipinfo="echo; curl -s https://icanhazip.com; echo; curl -s https://ipinfo.io | jq --indent 4 --sort-keys --color-output '. |= del(.readme)'"
alias cachefly="wget -O /dev/null https://cachefly.cachefly.net/100mb.test"
alias ie8vbox="wget -O /dev/null https://az792536.vo.msecnd.net/vms/VMBuild_20150916/VirtualBox/IE8/IE8.Win7.VirtualBox.zip"
alias linode="wget -O /dev/null http://speedtest.newark.linode.com/100MB-newark.bin"
alias iperf="iperf3 -c 192.34.85.234 -p 15201 --verbose"
