[[columns]]
kind = "Pid"
style = "Yellow"

[[columns]]
kind = "User"
style = "BrightGreen"

# [[columns]]
# kind = "TcpPort"
# style = "BrightCyan"

# [[columns]]
# kind = "UdpPort"
# style = "BrightCyan"

[[columns]]
kind = "UsageMem"
style = "ByPercentage"

[[columns]]
kind = "UsageCpu"
style = "ByPercentage"

[[columns]]
kind = "CpuTime"
style = "Cyan"

[[columns]]
kind = "StartTime"
style = "Magenta"

[[columns]]
kind = "Separator"
style = "White"

[[columns]]
kind = "Command"
style = "White"

[sort]
column = 5
order = "Ascending"

[pager]
mode = "Disable"
