add_newline = true
scan_timeout = 30

[character]
success_symbol = "[█](green)"
error_symbol = "[█](red)"
symbol = "█"
# error_symbol = "✖"
# use_symbol_for_status = true

[cmd_duration]
min_time = 1000
show_milliseconds = false
style = "yellow"

[directory]
style = "fg:blue bg:16 bold"
# style = "fg:16 bg:blue bold"
truncate_to_repo = false
truncation_length = -1
# prefix = " in "

[git_branch]
symbol = ""
# symbol = "ᚬ ᚼ ᛅ ᛘ ᛦ ᛋ ⑆ "
# [git_commit]
# disabled = true
# only_detached = false
# [git_state]
# disabled = true
[git_status]
disabled = true
# show_sync_count = true
# conflicted_count = true
# untracked_count = true
# stashed_count = true
# modified_count = true
# staged_count = true
# renamed_count = true
# deleted_count = true

[battery]
disabled = true

[time]
disabled = true

[hostname]
style = "red bold"

# ████  disables  ████

[aws]
disabled = true

[dart]
disabled = true

[dotnet]
disabled = true

[env_var]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true

[php]
disabled = true

[golang]
disabled = true

[java]
disabled = true

[package]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[username]
show_always = true
disabled = true

# [memory_usage]
# disabled = false
# show_percentage = true
# show_swap = true
# threshold = -1
# symbol = ""
# separator = "|"
# style = "dimmed"
